kind: Service
apiVersion: v1
metadata:
  name: item-service
spec:
  selector:
    app: item-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: item-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: item-service
    spec:
      volumes:
        - name: overops-agent
          emptyDir: {}
      initContainers:
        - name: overops-agent
          image: overops/agent-sidecar:alpine-latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - name: overops-agent
              mountPath: /takipi
      containers:
        - name: item-service
          image: bmorrise/item-service:@IMAGE_VERSION@
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          env:
            - name: TAKIPI_COLLECTOR_HOST
              value: "overops-collector-service"
            - name: TAKIPI_COLLECTOR_PORT
              value: "6060"
            - name: JAVA_TOOL_OPTIONS
              # example only - update application.name and deployment.name for your app
              value: "-agentpath:/takipi/lib/libTakipiAgent.so=takipi.application.name=item-service,takipi.deployment.name=v1.0"
            - name: MONGODB_HOST
              value: mongodb-service
            - name: CONTEXT_PATH
              value: /item-service
          volumeMounts:
            - name: overops-agent
              mountPath: /takipi
          ports:
            - containerPort: 8080
