spring:
  application:
    name: item-service
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      database: admin
server:
  port: 8080
  servlet:
    context-path: ${CONTEXT_PATH}
